version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building...
      - process.env.ACCESS_KEY=${ACCESS_KEY}
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist